#include "textconsts.h"

const char * const ELEMENTS[] = {
	"Infernal",
	"Frigid",
	"Heavenly",
	"Baleful"
};
const char * const STATUSES[] = {
	"Poison",
	"Extra Poison",
	"Paralysis",
	"Weakness",
	"Barrier",
	"Regen",
	"Fast",
	"Inviso",
};
const char * const ACC_DESC[] = {
	"Prevents poison",
	"Regenerates Qi during battle",
	"Gives an extra turn in battle",
	"Prevents all negative status conditions",
	"Keeps wearer's Qi completely filled during battle",
};
const char * const BATTLE_MENU[] = {
	"Attack",
	"Use spirit technique",
	"Defend",
	"Pass",
	"Escape",
};

const char * const CREDITS[] = {
  "With the rival clans expelled from the Oubliette,",
  "the Qilin clan's legacy has been secured.",
  "",
  "The spirit crystals and godrelics retrieved by",
  "Qilin Hawk and Qilin Star will be used to",
  "support the younger generation for centuries",
  "to come, further cementing the Qilin clan's",
  "position in the immortal world.",
  "",
  "",
  "",
  "",
  "",
  "INHERITORS of the OUBLIETTE",
  "----------       ---------",
  "",
  "(c) 2021 \x7FSOFT",
  "",
  "",
  "--- Credits ---",
  "",
  "GAME DESIGN:",
  "",
  "Mahou Shoujo * Magical Moestar",
  "one60hp",
  "",
  "",
  "PROGRAMMING:",
  "",
  "Mahou Shoujo * Magical Moestar",
  "",
  "",
  "GRAPHICS:",
  "",
  "one60hp",
  "",
  "",
  "MUSIC:",
  "",
  "one60hp",
  "",
  "",
  "LEVEL DESIGN:",
  "",
  "one60hp",
  "",
  "",
  "",
  "Thanks for playing!",
};
const size_t CREDITS_NUM = sizeof(CREDITS) / sizeof(CREDITS[0]);
